### ISSUE TITLE
AttributeError: 'FlaskOptimize' object has no attribute 'init_app'

### ISSUE THREAD

**Issue by oleksandr-l5** [sunary/flask-optimize#2]
subj

**Comment by sunary** [comment]
Its seem version 0.2.0 not display in https://pypi.python.org/pypi, so you must install from github instead install from pip.
Sorry about this inconvenience.

**Comment by sunary** [comment]
Published to pypi, pls reinstall `flask-optimize` from pip

**Comment by oleksandr-l5** [comment]
Thanks
