### ISSUE TITLE
ImportError: cannot import name FlaskOptimize

### ISSUE THREAD

**Issue by 5kyc0d3r** [sunary/flask-optimize#4]
Hi, I installed flask-optimize from the Github repository with `$ sudo python setup.py install` and it got installed successfully. After that I imported it just like in the example in the README file, like
```python
from flask_optimize import FlaskOptimize
```
But I keep getting `ImportError: cannot import name FlaskOptimize`
Do you know what the problem could be? I am running `Python 2.7` on `Ubuntu 16.04`.

**Comment by sunary** [comment]
Fixed, Please upgrade new version.
Thanks for your issue
