### ISSUE TITLE
Conflicts with frozen-flask

### ISSUE THREAD

**Issue by stucka** [sunary/flask-optimize#5]
Something strange happens when I try using this with Frozen Flask; seems like something's crashing, then getting binary content ... ?

I get properly minified HTML from regular live flask; I get proper output from non-optimized frozen-flask. And I get garbage binary stuff from optimized frozen.

**Comment by sunary** [comment]
**Flask Optimize** will compress your website to `gzip` before freeze into static file.
You can disable it in `config`:
```python
config_update = {'html': {'htmlmin': True,  'izip': False, 'cache': 'GET-84600'},
                            'json': {'htmlmin': False, 'izip': False, 'cache': False},
                            'text': {'htmlmin': False, 'izip': False, 'cache': 84600}}
flask_optimize = FlaskOptimize(config_update=config_update)
```

**Comment by stucka** [comment]
Edit: That worked! I had missed a step on the first try. Thank you so very much! This is wonderful. You just shaved off 60k from one file, and I'm much obliged.
