### ISSUE TITLE
basestring not compatible with python3

### ISSUE THREAD

**Issue by koyo922** [sunary/flask-optimize#6]
https://github.com/sunary/flask-optimize/blob/bd6f7212bfbbaa350b246428530db0460c1f167d/flask_optimize/optimize.py#L89

python3 can not resolve `basestring`;
even you are using a tuple like `(str, basestring)`, both need to be recognizable, or else NameError.
using `Python 3.6.4 :: Anaconda, Inc.`

> NameError: name 'basestring' is not defined

**Comment by sunary** [comment]
Solved in this commit, and update new version in pypi:
https://github.com/sunary/flask-optimize/commit/e4862be94da3b9f73e56656afa1e964ec4a9ee80

Thank for your issue.
